In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
voice_df = pd.read_csv("/content/drive/MyDrive/Home Practice Datasets/voice.csv")
voice_df.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male

In [ ]:
voice_df.corr()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,mode,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx
meanfreq,1.000000,-0.739039,0.925445,0.911416,0.740997,-0.627605,-0.322327,-0.316036,-0.601203,-0.784332,0.687715,1.000000,0.460844,0.383937,0.274004,0.536666,0.229261,0.519528,0.515570,-0.216979
sd,-0.739039,1.000000,-0.562603,-0.846931,-0.161076,0.874660,0.314597,0.346241,0.716620,0.838086,-0.529150,-0.739039,-0.466281,-0.345609,-0.129662,-0.482726,-0.357667,-0.482278,-0.475999,0.122660
median,0.925445,-0.562603,1.000000,0.774922,0.731849,-0.477352,-0.257407,-0.243382,-0.502005,-0.661690,0.677433,0.925445,0.414909,0.337602,0.251328,0.455943,0.191169,0.438919,0.435621,-0.213298
Q25,0.911416,-0.846931,0.774922,1.000000,0.477140,-0.874189,-0.319475,-0.350182,-0.648126,-0.766875,0.591277,0.911416,0.545035,0.320994,0.199841,0.467403,0.302255,0.459683,0.454394,-0.141377
Q75,0.740997,-0.161076,0.731849,0.477140,1.000000,0.009636,-0.206339,-0.148881,-0.174905,-0.378198,0.486857,0.740997,0.155091,0.258002,0.285584,0.359181,-0.023750,0.335114,0.335648,-0.216475
IQR,-0.627605,0.874660,-0.477352,-0.874189,0.009636,1.000000,0.249497,0.316185,0.640813,0.663601,-0.403764,-0.627605,-0.534462,-0.222680,-0.069588,-0.333362,-0.357037,-0.337877,-0.331563,0.041252
skew,-0.322327,0.314597,-0.257407,-0.319475,-0.206339,0.249497,1.000000,0.977020,-0.195459,0.079694,-0.434859,-0.322327,-0.167668,-0.216954,-0.080861,-0.336848,-0.061608,-0.305651,-0.304640,-0.169325
kurt,-0.316036,0.346241,-0.243382,-0.350182,-0.148881,0.316185,0.977020,1.000000,-0.127644,0.109884,-0.406722,-0.316036,-0.194560,-0.203201,-0.045667,-0.303234,-0.103313,-0.274500,-0.272729,-0.205539
sp.ent,-0.601203,0.716620,-0.502005,-0.648126,-0.174905,0.640813,-0.195459,-0.127644,1.000000,0.866411,-0.325298,-0.601203,-0.513194,-0.305826,-0.120738,-0.293562,-0.294869,-0.324253,-0.319054,0.198074
sfm,-0.784332,0.838086,-0.661690,-0.766875,-0.378198,0.663601,0.079694,0.109884,0.866411,1.000000,-0.485913,-0.784332,-0.421066,-0.362100,-0.192369,-0.428442,-0.289593,-0.436649,-0.431580,0.211477
mode,0.687715,-0.529150,0.677433,0.591277,0.486857,-0.403764,-0.434859,-0.406722,-0.325298,-0.485913,1.000000,0.687715,0.324771,0.385467,0.172329,0.491479,0.198150,0.477187,0.473775,-0.182344
centroid,1.000000,-0.739039,0.925445,0.911416,0.740997,-0.627605,-0.322327,-0.316036,-0.601203,-0.784332,0.687715,1.000000,0.460844,0.383937,0.274004,0.536666,0.229261,0.519528,0.515570,-0.216979
meanfun,0.460844,-0.466281,0.414909,0.545035,0.155091,-0.534462,-0.167668,-0.194560,-0.513194,-0.421066,0.324771,0.460844,1.000000,0.339387,0.311950,0.270840,0.162163,0.277982,0.275154,-0.054858
minfun,0.383937,-0.345609,0.337602,0.320994,0.258002,-0.222680,-0.216954,-0.203201,-0.305826,-0.362100,0.385467,0.383937,0.339387,1.000000,0.213987,0.375979,0.082015,0.317860,0.316486,0.002042
maxfun,0.274004,-0.129662,0.251328,0.199841,0.285584,-0.069588,-0.080861,-0.045667,-0.120738,-0.192369,0.172329,0.274004,0.311950,0.213987,1.000000,0.337553,-0.243426,0.355390,0.359880,-0.363029
meandom,0.536666,-0.482726,0.455943,0.467403,0.359181,-0.333362,-0.336848,-0.303234,-0.293562,-0.428442,0.491479,0.536666,0.270840,0.375979,0.337553,1.000000,0.099656,0.812838,0.811304,-0.180954
mindom,0.229261,-0.357667,0.191169,0.302255,-0.023750,-0.357037,-0.061608,-0.103313,-0.294869,-0.289593,0.198150,0.229261,0.162163,0.082015,-0.243426,0.099656,1.000000,0.026640,0.008666,0.200212
maxdom,0.519528,-0.482278,0.438919,0.459683,0.335114,-0.337877,-0.305651,-0.274500,-0.324253,-0.436649,0.477187,0.519528,0.277982,0.317860,0.355390,0.812838,0.026640,1.000000,0.999838,-0.425531
dfrange,0.515570,-0.475999,0.435621,0.454394,0.335648,-0.331563,-0.304640,-0.272729,-0.319054,-0.431580,0.473775,0.515570,0.275154,0.316486,0.359880,0.811304,0.008666,0.999838,1.000000,-0.429266
modindx,-0.216979,0.122660,-0.213298,-0.141377,-0.216475,0.041252,-0.169325,-0.205539,0.198074,0.211477,-0.182344,-0.216979,-0.054858,0.002042,-0.363029,-0.180954,0.200212,-0.425531,-0.429266,1.000000

In [ ]:
voice_df.columns

Index(['meanfreq', 'sd', 'median', 'Q25', 'Q75', 'IQR', 'skew', 'kurt',
       'sp.ent', 'sfm', 'mode', 'centroid', 'meanfun', 'minfun', 'maxfun',
       'meandom', 'mindom', 'maxdom', 'dfrange', 'modindx', 'label'],
      dtype='object')

In [ ]:
voice_df.shape

(3168, 21)

In [ ]:
voice_df.describe()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,mode,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx
count,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000,3168.000000
mean,0.180907,0.057126,0.185621,0.140456,0.224765,0.084309,3.140168,36.568461,0.895127,0.408216,0.165282,0.180907,0.142807,0.036802,0.258842,0.829211,0.052647,5.047277,4.994630,0.173752
std,0.029918,0.016652,0.036360,0.048680,0.023639,0.042783,4.240529,134.928661,0.044980,0.177521,0.077203,0.029918,0.032304,0.019220,0.030077,0.525205,0.063299,3.521157,3.520039,0.119454
min,0.039363,0.018363,0.010975,0.000229,0.042946,0.014558,0.141735,2.068455,0.738651,0.036876,0.000000,0.039363,0.055565,0.009775,0.103093,0.007812,0.004883,0.007812,0.000000,0.000000
25%,0.163662,0.041954,0.169593,0.111087,0.208747,0.042560,1.649569,5.669547,0.861811,0.258041,0.118016,0.163662,0.116998,0.018223,0.253968,0.419828,0.007812,2.070312,2.044922,0.099766
50%,0.184838,0.059155,0.190032,0.140286,0.225684,0.094280,2.197101,8.318463,0.901767,0.396335,0.186599,0.184838,0.140519,0.046110,0.271186,0.765795,0.023438,4.992188,4.945312,0.139357
75%,0.199146,0.067020,0.210618,0.175939,0.243660,0.114175,2.931694,13.648905,0.928713,0.533676,0.221104,0.199146,0.169581,0.047904,0.277457,1.177166,0.070312,7.007812,6.992188,0.209183
max,0.251124,0.115273,0.261224,0.247347,0.273469,0.252225,34.725453,1309.612887,0.981997,0.842936,0.280000,0.251124,0.237636,0.204082,0.279114,2.957682,0.458984,21.867188,21.843750,0.932374

In [ ]:
voice_df.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [ ]:
voice_df['label'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
#Total Count of Each Categorical Value in column
print("Total no of males :", len(voice_df[voice_df['label'] == 'male']))
print("Total no of females :", len(voice_df[voice_df['label']== 'female']))

Total no of males : 1584
Total no of females : 1584

In [ ]:
X = voice_df.iloc[:,:-1]
X.head()

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,mode,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,0.000000,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,0.000000,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,0.000000,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,0.083878,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,0.104261,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274

In [ ]:
y = voice_df.iloc[:,-1]
y.head()

0    male
1    male
2    male
3    male
4    male
Name: label, dtype: object

In [ ]:
#Converting the target ('label') values into '0'and '1'
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
Scaler.fit(X)
X = Scaler.transform(X)
X

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

In [ ]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 , random_state= 1)

In [ ]:
#Using SVM with default hyperparameter
from sklearn.svm import SVC
from sklearn import metrics
svc =SVC()
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Accuracy Score :", metrics.accuracy_score(y_test, y_pred))

Accuracy Score : 0.9763406940063092

In [ ]:
#Using Linear Kernel
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Accuracy Score:", metrics.accuracy_score(y_pred,y_test))

Accuracy Score: 0.9779179810725552

In [ ]:
#Using RBF Kernel
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Accuracy Score:", metrics.accuracy_score(y_pred,y_test))

Accuracy Score: 0.9763406940063092

In [ ]:
#Using Polynomial Kernel
svc = SVC(kernel='poly')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Accuracy Score:", metrics.accuracy_score(y_pred,y_test))

Accuracy Score: 0.9589905362776026

In [ ]:
#Performing K-fold cross validation with different kernels
from sklearn.model_selection import cross_val_score
svc = SVC(kernel='linear')
scores = cross_val_score(svc, X, y, cv = 10, scoring = 'accuracy')
print("Scores are :", scores)
print("Mean Scores are :", scores.mean())

Scores are : [0.91167192 0.97160883 0.97160883 0.97791798 0.95899054 0.9873817
 0.99369085 0.97791798 0.95253165 0.99367089]
Mean Scores are : 0.9696991175178692

In [ ]:
svc = SVC(kernel='rbf')
scores = cross_val_score(svc, X, y, cv = 10, scoring = 'accuracy')
print("Scores are :", scores)
print("Mean Scores are :", scores.mean())

Scores are : [0.93375394 0.95583596 0.96845426 0.96214511 0.96529968 0.99684543
 0.99053628 0.98422713 0.91455696 0.99367089]
Mean Scores are : 0.9665325639899376

In [ ]:
svc = SVC(kernel='poly')
scores = cross_val_score(svc, X, y, cv = 10, scoring = 'accuracy')
print("Scores are :", scores)
print("Mean Scores are :", scores.mean())

Scores are : [0.89274448 0.94952681 0.93059937 0.92744479 0.94952681 0.99369085
 0.98422713 0.96529968 0.87974684 0.9778481 ]
Mean Scores are : 0.9450654873617378

In [ ]:
C_range = list(range(1,26))
acc_score = []
for c in C_range:
  svc = SVC(kernel='linear', C=c)
  scores = cross_val_score(svc, X, y, cv = 10, scoring = 'accuracy')
  acc_score.append(scores.mean())
print(acc_score)

[0.9696991175178692, 0.969068202691371, 0.969068202691371, 0.969068202691371, 0.9693836601046201, 0.9693836601046201, 0.969068202691371, 0.9687527452781215, 0.9684372878648724, 0.9684372878648724, 0.9684372878648724, 0.9684372878648724, 0.9681208321686698, 0.9681208321686698, 0.9681208321686698, 0.9681208321686698, 0.9678043764724673, 0.9678043764724673, 0.9678043764724673, 0.9678043764724673, 0.9681208321686698, 0.968436289581919, 0.968436289581919, 0.9681198338857164, 0.9681198338857164]